### ISSUE TITLE
Problém s ?..... v proměnných 

### ISSUE THREAD

**Issue by kalich5** [mhujer/fio-api-php#14]
Ve dvou souborech API 
https://github.com/mhujer/fio-api-php/blob/master/src/FioApi/Transaction.php
https://github.com/mhujer/fio-api-php/blob/master/src/FioApi/TransactionList.php

Jsou proměnné s **?......** a když to máme zakomponované v pluginu pro WordPress, vůbec mě to nepustí dál. Píše to chybu PHP syntax error

**Comment by tomasfejfar** [comment]
[Nullable typehint jsou od PHP7.1](http://php.net/manual/en/migration71.new-features.php#migration71.new-features.nullable-types). Nejspíš máte PHP 7.0. Jestli máš teda na mysli třeba `?float $idFrom,`

**Comment by kalich5** [comment]
Jo, přesně tohle nechce pustit při uploadu do repozitáře. A i Dreamweave, hlásí chybu syntaxe

**Comment by kalich5** [comment]
![bez nazvu](https://user-images.githubusercontent.com/8988898/40015478-c7d0a5c2-57b3-11e8-8cb3-8b5690b6a9ff.png)

**Comment by tomasfejfar** [comment]
A jak se vám to tam podařilo nainstalovat? [Přímo v composeru je dependency](https://github.com/mhujer/fio-api-php/blob/master/composer.json#L21) na to, že to musí mít 7.1.

**Comment by kalich5** [comment]
Když si to stáhnu z githubu https://github.com/skaut/skaut-fio-bank-transactions/ z našeho repozitáře, tak to samozřejmě funguje

Ale nejde to nahrát do repozitáře, pro další uživatele...

**Comment by tomasfejfar** [comment]
No, teoreticky pomůže změnit verzi PHP v composeru v tom pluginu: https://github.com/skaut/skaut-fio-bank-transactions/blob/master/composer.json#L20 na 7.1

Každopádně to nijak nesouvisí s touhle knihovnou. Ta prostě vyžaduje PHP 7.1 a pokud je spuštěna na 7.0, tak logicky vyhodí syntax error.
