### ISSUE TITLE
Nenacita se certifikat

### ISSUE THREAD

**Issue by landsman** [mhujer/fio-api-php#16]
Ahoj,
napada te proc by se nemel nacist certifikat?

`Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /localhost/primaplatba/report/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186 Stack trace: #0 /localhost/primaplatba/report/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /localhost/primaplatba/report/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /localhost/primaplatba/report/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), in /localhost/primaplatba/report/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186
`

**Comment by mhujer** [comment]
@landsman Jak přesně to voláš?

Kdyžtak zkus nainstalovat [composer/ca-bundle](https://github.com/composer/ca-bundle/), začne ho to pak automaticky používat: https://github.com/mhujer/fio-api-php/blob/7a6e67540c186aa1c892808cac842982d22ab590/src/FioApi/Downloader.php#L30-L49

**Comment by landsman** [comment]
Měl jsem asi nějaký problém s nastavením PHP. Přepnul jsem na localhostu z apache na nginx a začlo to chodit, divné.

**Comment by mhujer** [comment]
Tak to je fakt divné. Ale pokud jsi instaloval nginx, tak je možné, že to přitom updatnulo systémové certifikáty?

**Comment by landsman** [comment]
To si nemyslím, já ho pouze zapnul, už jsem ho tu měl.

**Comment by mhujer** [comment]
Aha, tak holt nějaká anomálie.

**Comment by pavel-janicek** [comment]
Měl jsem podobný problém. Vyřešil jsem to takto
1. Stáhnout root certifkát z https://curl.haxx.se/ca/cacert.pem
2. Daný certifikát jsem uložil do https://github.com/mhujer/fio-api-php/tree/master/src/FioApi/keys

Později jsem pak nastavil takto v kódu:
```
$downloader = new FioApi\Downloader('API_TOKEN');
$downloader->setCertificatePath(__DIR__ . '/vendor/mhujer/fio-api-php/src/FioApi/keys/cacert.pem');
```
zatím to vypadá, že toto vyřešilo problém
