### ISSUE TITLE
PHP7 a datové typy

### ISSUE THREAD

**Issue by soukicz** [mhujer/fio-api-php#8]
Koukám, že už je dropnuté PHP5. Nechtělo by to ale rovnou i upravit argumenty, ať mají hezky datové typy? Když už se dělá nová major verze...
Klidně pošlu PR, ale moc se mi nechce drbat s code style :))

**Comment by mhujer** [comment]
Já už tu knihovnu nepoužívám na ničem běžícím, takže jsem se je bál doplnit, aby se to pak někde nevysypalo. Navrhuju, že to udělám v branchi, ty to otestuješ na reálných datech a pak to dáme do masteru, což?

**Comment by soukicz** [comment]
Klidně. Já si právě říkal, že major verze je pro to ideální příležitost.

**Comment by mhujer** [comment]
TODO:
- [ ] datové typy
- [ ] DateTimeImmutable

**Comment by mhujer** [comment]
Nakonec jsem to vzal ještě o něco šířeji - https://github.com/mhujer/fio-api-php/pull/9
